/* Generated By:JJTree: Do not edit this line. ASTArrayElement.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTArrayElement extends SimpleNode {
  public String content; 

  public ASTArrayElement(int id) {
    super(id);
    type = Utils.ARRAY;
  }

  public ASTArrayElement(Parser p, int id) {
    super(p, id);
  }

  public String toString(String prefix) {
    value = content;
    return prefix + value + "[]";
  }
}
/* JavaCC - OriginalChecksum=bfb423163e1035ee48f8712c238c8a4e (do not edit this line) */
