/* Generated By:JJTree: Do not edit this line. ASTArgumentList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTArgumentList extends SimpleNode {
  public ASTArgumentList(int id) {
    super(id);
  }

  public ASTArgumentList(yal2jvm p, int id) {
    super(p, id);
  }

  public String toString(String prefix) {
  	return prefix + "Argument List: ";
  }

}
/* JavaCC - OriginalChecksum=e237b3360f6401ab7120f5cc19841021 (do not edit this line) */
