/* Generated By:JJTree: Do not edit this line. ASTArraySize.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTArraySize extends SimpleNode {
  public ASTArraySize(int id) {
    super(id, "Array");
  }

  public ASTArraySize(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=17761e5d1d57f3599b5080e09d0764f6 (do not edit this line) */
