/* Generated By:JJTree: Do not edit this line. ASTCall.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTCall extends SimpleNode {
  public String calledFunction;
  
  public ASTCall(int id) {
    super(id);
    type = Utils.CALL;
  }

  public ASTCall(Parser p, int id) {
    super(p, id);
  }

  public String toString(String prefix) {
  	if (calledFunction != null) {
      value = calledFunction;
      return prefix + "Called " + calledFunction;
    }
    return null;
  }

}
/* JavaCC - OriginalChecksum=5206d28e366ee8ca4b52058e60679d46 (do not edit this line) */
