/* Generated By:JJTree: Do not edit this line. ASTDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDeclaration extends SimpleNode {
  public ASTDeclaration(int id) {
    super(id);
  }

  public ASTDeclaration(Parser p, int id) {
    super(p, id);
  }

  public String toString(String prefix) {
  	return prefix + "ASTDeclaration";
  }

}
/* JavaCC - OriginalChecksum=cca9b8b7b7b42df531649f29f30a7ccb (do not edit this line) */
