/* Generated By:JJTree: Do not edit this line. ASTDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDeclaration extends SimpleNode {
  private boolean isNegative = false;
  private String assignedValue;

  public ASTDeclaration(int id) {
    super(id);
  }

  public ASTDeclaration(yal2jvm p, int id) {
    super(p, id);
  }

  public String toString(String prefix) {
  	return prefix + "ASTDeclaration";
  }

  public void setOperator(String operator) {
    System.out.println("SET OPERATOR DECLARATION");
    if (operator.equals("-")) 
      isNegative = true;
    else 
      isNegative = false;
  }

  public void setAssigned(String toAssign) {
    assignedValue = toAssign;
  }

  public String getAssignedValue() {
    return assignedValue;
  }

}
/* JavaCC - OriginalChecksum=cca9b8b7b7b42df531649f29f30a7ccb (do not edit this line) */
