/* Generated By:JJTree: Do not edit this line. ASTerror_skipto.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTerror_skipto extends SimpleNode {
  public ASTerror_skipto(int id) {
    super(id);
  }

  public ASTerror_skipto(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4686789ee60711927b4fdab2b1ec1374 (do not edit this line) */
