/* Generated By:JJTree: Do not edit this line. ASTerror_skipto_unless.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTerror_skipto_unless extends SimpleNode {
  public ASTerror_skipto_unless(int id) {
    super(id);
  }

  public ASTerror_skipto_unless(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=875fba66b4ab404b48eab4d5860597ae (do not edit this line) */
