/* Generated By:JJTree: Do not edit this line. ASTerror_skipto_unless.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTerror_skipto_unless extends SimpleNode {
  public ASTerror_skipto_unless(int id) {
    super(id);
  }

  public ASTerror_skipto_unless(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c004c9c50f02bba010ccb29909c0c2a6 (do not edit this line) */
