/* Generated By:JJTree: Do not edit this line. ASTerror_skipto_withoutconsuming.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTerror_skipto_withoutconsuming extends SimpleNode {
  public ASTerror_skipto_withoutconsuming(int id) {
    super(id);
  }

  public ASTerror_skipto_withoutconsuming(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=55b7bfa990b4aec82c3a46c8536a23cd (do not edit this line) */
