/* Generated By:JJTree: Do not edit this line. ASTLhsNoID.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLhsNoID extends SimpleNode {
  public String lhsNoIDContent;

  public ASTLhsNoID(int id) {
    super(id);
  }

  public ASTLhsNoID(Parser p, int id) {
    super(p, id);
  }

  public String toString(String prefix) {
  	return prefix + lhsNoIDContent;
  }

}
/* JavaCC - OriginalChecksum=1d02fa7c1600eedd97bbbe22c860fede (do not edit this line) */
