/* Generated By:JJTree: Do not edit this line. ASTLhs.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLhs extends SimpleNode {
  public ASTLhs(int id) {
    super(id);
  }

  public ASTLhs(Parser p, int id) {
    super(p, id);
  }

  public String toString(String prefix) {
  	return prefix + "ASTLhs";
  }

}
/* JavaCC - OriginalChecksum=8917a341c6a2ee41a277aa7de2652499 (do not edit this line) */
