/* Generated By:JJTree: Do not edit this line. ASTStmtlst.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTStmtlst extends SimpleNode {
  
  public String value;
  public ASTStmtlst(int id) {
    super(id);
  }

  public ASTStmtlst(yal2jvm p, int id) {
    super(p, id);
  }
}
/* JavaCC - OriginalChecksum=8543c3d21476b95d301065aa404e9bd2 (do not edit this line) */
