/* Generated By:JJTree: Do not edit this line. ASTStmt.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTStmt extends SimpleNode {

 
  public ASTStmt(int id) {
    super(id);
  }

  public ASTStmt(Parser p, int id) {
    super(p, id);
  }


}
/* JavaCC - OriginalChecksum=74be137c7d22c55c529778978dff2e79 (do not edit this line) */
