/* Generated By:JJTree: Do not edit this line. ASTVarListChildren.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTVarListChildren extends SimpleNode {

	public String var;

	public ASTVarListChildren(int id) {
		super(id);
	}

	public ASTVarListChildren(Parser p, int id) {
		super(p, id);
	}

	public String toString(String prefix) {
  	if (var != null)
  		return prefix + "VarList (" + var + " )";
  	else
  		return "";
  }

}
/* JavaCC - OriginalChecksum=52dceacf43d57a921405e95ddd9697f3 (do not edit this line) */
