/* Generated By:JJTree: Do not edit this line. ASTVar.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTVar extends SimpleNode {
  public ASTVar(int id) {
    super(id);
  }

  public ASTVar(yal2jvm p, int id) {
    super(p, id);
  }

  public String toString(String prefix) {
    if (value != null)
      return prefix + value;

    return null;
  }

}
/* JavaCC - OriginalChecksum=2c65a3497e7c846edad835bf238bc727 (do not edit this line) */
