/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 7.0.2 */
public interface ParserTreeConstants
{
  public int JJTMODULE = 0;
  public int JJTFUNCTION = 1;
  public int JJTDECLARATION = 2;
  public int JJTVARLIST = 3;
  public int JJTVOID = 4;
  public int JJTCALL = 5;
  public int JJTASSIGN = 6;
  public int JJTWHILE = 7;
  public int JJTIF = 8;
  public int JJTELSE = 9;
  public int JJTTERM = 10;
  public int JJTEXPRTEST = 11;
  public int JJTARGUMENTLIST = 12;
  public int JJTARGUMENT = 13;
  public int JJTARRAYACCESS = 14;
  public int JJTARRAYINSTANTION = 15;
  public int JJTSCALARACCESS = 16;
  public int JJTVAR = 17;
  public int JJTARRAYELEMENT = 18;
  public int JJTERROR_SKIPTO = 19;
  public int JJTERROR_SKIPTO_UNLESS = 20;
  public int JJTERROR_SKIPTO_WITHOUTCONSUMING = 21;


  public String[] jjtNodeName = {
    "Module",
    "Function",
    "Declaration",
    "VarList",
    "void",
    "Call",
    "Assign",
    "While",
    "If",
    "Else",
    "Term",
    "Exprtest",
    "ArgumentList",
    "Argument",
    "ArrayAccess",
    "ArrayInstantion",
    "ScalarAccess",
    "Var",
    "ArrayElement",
    "error_skipto",
    "error_skipto_unless",
    "error_skipto_withoutconsuming",
  };
}
/* JavaCC - OriginalChecksum=b7dfae1159c3275516b98e992ec54727 (do not edit this line) */
