/* Generated By:JavaCC: Do not edit this line. yal2jvmTreeConstants.java Version 7.0.2 */
public interface yal2jvmTreeConstants
{
  public int JJTMODULE = 0;
  public int JJTFUNCTION = 1;
  public int JJTDECLARATION = 2;
  public int JJTVARLIST = 3;
  public int JJTVOID = 4;
  public int JJTCALL = 5;
  public int JJTASSIGN = 6;
  public int JJTWHILE = 7;
  public int JJTIF = 8;
  public int JJTELSE = 9;
  public int JJTRHS = 10;
  public int JJTTERM = 11;
  public int JJTEXPRTEST = 12;
  public int JJTARGUMENTLIST = 13;
  public int JJTARGUMENT = 14;
  public int JJTARRAYACCESS = 15;
  public int JJTARRAYINSTANTION = 16;
  public int JJTSCALARACCESS = 17;
  public int JJTVAR = 18;
  public int JJTARRAYELEMENT = 19;
  public int JJTERROR_SKIPTO = 20;
  public int JJTERROR_SKIPTO_UNLESS = 21;
  public int JJTERROR_SKIPTO_WITHOUTCONSUMING = 22;


  public String[] jjtNodeName = {
    "Module",
    "Function",
    "Declaration",
    "VarList",
    "void",
    "Call",
    "Assign",
    "While",
    "If",
    "Else",
    "Rhs",
    "Term",
    "Exprtest",
    "ArgumentList",
    "Argument",
    "ArrayAccess",
    "ArrayInstantion",
    "ScalarAccess",
    "Var",
    "ArrayElement",
    "error_skipto",
    "error_skipto_unless",
    "error_skipto_withoutconsuming",
  };
}
/* JavaCC - OriginalChecksum=e7bb56d7aeb541a374d06ffeca74b6cb (do not edit this line) */
